version: "3.8"
services:
  node:
    build:
      context: ./api
      target: dev
    volumes:
      - ./api/index.js:/src/index.js
  nodebroaker:
    build:
      context: ./api2
      target: dev
    volumes:
      - ./api2/index.js:/src/index.js      
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 8089:80
    volumes:
      - ./html5up-stellar/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/custom.conf:/etc/nginx/nginx.conf
    depends_on:
      - node
